### ISSUE TITLE
关于对linux服务器的自动运维

### ISSUE THREAD

**Issue by jhzhujianhui** [icefire-ken/devices_inspection#1]
想问一下，我测试的是linux服务器，开启了ssh登录，但测试发现有个enable的认证，服务器不需要，请问该如何修改呢？？

**Comment by icefire-ken** [comment]
你好
这个脚本是为网工巡检网络设备用的，并没有针对Linux服务器设备。
当中核心模块netmiko也是用来针对网络设备使用的，并不支持linux。


















在 2023-12-27 14:25:09，"jhzhujianhui" ***@***.***> 写道：

想问一下，我测试的是linux服务器，开启了ssh登录，但测试发现有个enable的认证，服务器不需要，请问该如何修改呢？？

**Comment by icefire-ken** [comment]
抱歉，之前的回复有误。
今天看了一下netmiko支持的设备类型，是有linux的
理论上在info文件里添加设备登录信息，device_type列里填linux，再到sheet2里填写一些linux巡检命令，即可
下周我会进行下测试，有消息通知你













在 2023-12-27 14:25:09，"jhzhujianhui" ***@***.***> 写道：

想问一下，我测试的是linux服务器，开启了ssh登录，但测试发现有个enable的认证，服务器不需要，请问该如何修改呢？？

**Comment by icefire-ken** [comment]
我简单做了下测试，是可以的
登录信息中secret字段空着就行


简单从网上找了几个linux的巡检命令


结果是这样的






希望能帮到你解决问题







在 2023-12-27 14:25:09，"jhzhujianhui" ***@***.***> 写道：

想问一下，我测试的是linux服务器，开启了ssh登录，但测试发现有个enable的认证，服务器不需要，请问该如何修改呢？？
