### ISSUE TITLE
建议增加一个查询本机时间的功能

### ISSUE THREAD

**Issue by joyhu** [icefire-ken/devices_inspection#10]
在巡检时会查询设备的时间，但是批量巡检设备后即使查询了也无法确认时间是否正常。是否要以增加一个查询主机时间的功能，在巡检查询设备时间下一行就可以输入这个命令，这样就可以使用两个时间做对比。

**Comment by icefire-ken** [comment]
我可能会把这个本机时间放在最前面，这样方便一些。

**Comment by icefire-ken** [comment]
> 在巡检时会查询设备的时间，但是批量巡检设备后即使查询了也无法确认时间是否正常。是否要以增加一个查询主机时间的功能，在巡检查询设备时间下一行就可以输入这个命令，这样就可以使用两个时间做对比。

在95行（for cmd in cmds_dict[login_info['device_type']]:）之上插入：
device_log_file.write('=' * 10 + ' ' + '本机时间' + ' ' + '=' * 10 + '\n\n')
device_log_file.write(time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()) + '\n\n')

**Comment by icefire-ken** [comment]
> 在巡检时会查询设备的时间，但是批量巡检设备后即使查询了也无法确认时间是否正常。是否要以增加一个查询主机时间的功能，在巡检查询设备时间下一行就可以输入这个命令，这样就可以使用两个时间做对比。

已经更新了代码，我觉得还不错。
