### ISSUE TITLE
关于运行python文件提示没有info文件的问题

### ISSUE THREAD

**Issue by baooox** [icefire-ken/devices_inspection#11]
如题：
关于运行python文件提示没有info文件的问题，但是运行python调试文件就可以顺利进行，这个该怎么解决啊

**Comment by icefire-ken** [comment]
> 如题： 关于运行python文件提示没有info文件的问题，但是运行python调试文件就可以顺利进行，这个该怎么解决啊

直接运行exe文件，还是运行py文件，都是可以的。
在运行使用脚本时会让你输入info文件名称，是不是无意间输入了空格或其他无效的info文件名。
