### ISSUE TITLE
关于打包大小的问题

### ISSUE THREAD

**Issue by boluo123432423** [icefire-ken/Devices_Inspection#2]
我怎么打包出来特别大，想问一下是怎么打包操作那么小的

**Comment by icefire-ken** [comment]
为你的项目创建一个虚拟环境，这个虚拟环境里只安装跟这个项目相关的第三方模块
打包的时候就不会包含其他没有用的模块了。
也有可能你的项目本身就用到很多模块，也可能造成打包结果很大。
















在 2024-01-04 09:33:11，"boluo123432423" ***@***.***> 写道：

我怎么打包出来特别大，想问一下是怎么打包操作那么小的
