### ISSUE TITLE
如何自行增加其它类型的设备

### ISSUE THREAD

**Issue by joyhu** [icefire-ken/devices_inspection#4]
请问我想自己增加其它类型的设备是不是在https://ktbyers.github.io/netmiko/docs/netmiko/index.html中找到可以支持的设备，并将对应的类型写到info.xlsx中的drvice_type，然后增加对应的巡检命令即可。谢谢！

**Comment by icefire-ken** [comment]
> 请问我想自己增加其它类型的设备是不是在[https://ktbyers.github.io/netmiko/docs/netmiko/index.html中找到可以支持的设备，并将对应的类型写到info.xlsx中的drvice_type，然后增加对应的巡检命令即可。谢谢！](https://ktbyers.github.io/netmiko/docs/netmiko/index.html%E4%B8%AD%E6%89%BE%E5%88%B0%E5%8F%AF%E4%BB%A5%E6%94%AF%E6%8C%81%E7%9A%84%E8%AE%BE%E5%A4%87%EF%BC%8C%E5%B9%B6%E5%B0%86%E5%AF%B9%E5%BA%94%E7%9A%84%E7%B1%BB%E5%9E%8B%E5%86%99%E5%88%B0info.xlsx%E4%B8%AD%E7%9A%84drvice_type%EF%BC%8C%E7%84%B6%E5%90%8E%E5%A2%9E%E5%8A%A0%E5%AF%B9%E5%BA%94%E7%9A%84%E5%B7%A1%E6%A3%80%E5%91%BD%E4%BB%A4%E5%8D%B3%E5%8F%AF%E3%80%82%E8%B0%A2%E8%B0%A2%EF%BC%81)

是的，你也可以在下面这个连接里找到 CLASS_MAPPER_BASE 这个字典，查看netmiko支持的设备类型
[CLASS_MAPPER_BASE](https://github.com/ktbyers/netmiko/blob/master/netmiko/ssh_dispatcher.py)

**Comment by joyhu** [comment]
> > 请问我想自己增加其它类型的设备是不是在[https://ktbyers.github.io/netmiko/docs/netmiko/index.html中找到可以支持的设备，并将对应的类型写到info.xlsx中的drvice_type，然后增加对应的巡检命令即可。谢谢！](https://ktbyers.github.io/netmiko/docs/netmiko/index.html%E4%B8%AD%E6%89%BE%E5%88%B0%E5%8F%AF%E4%BB%A5%E6%94%AF%E6%8C%81%E7%9A%84%E8%AE%BE%E5%A4%87%EF%BC%8C%E5%B9%B6%E5%B0%86%E5%AF%B9%E5%BA%94%E7%9A%84%E7%B1%BB%E5%9E%8B%E5%86%99%E5%88%B0info.xlsx%E4%B8%AD%E7%9A%84drvice_type%EF%BC%8C%E7%84%B6%E5%90%8E%E5%A2%9E%E5%8A%A0%E5%AF%B9%E5%BA%94%E7%9A%84%E5%B7%A1%E6%A3%80%E5%91%BD%E4%BB%A4%E5%8D%B3%E5%8F%AF%E3%80%82%E8%B0%A2%E8%B0%A2%EF%BC%81)
> 
> 是的，你也可以在下面这个连接里找到 CLASS_MAPPER_BASE 这个字典，查看netmiko支持的设备类型 [CLASS_MAPPER_BASE](https://github.com/ktbyers/netmiko/blob/master/netmiko/ssh_dispatcher.py)

感谢
