### ISSUE TITLE
linux服务器巡检问题

### ISSUE THREAD

**Issue by zZzZhangjh** [icefire-ken/devices_inspection#6]
我执行.exe文件的时候，linux是没有enable这个选项的，但是cmd窗口告知巡检失败了。

**Comment by icefire-ken** [comment]
> 我执行.exe文件的时候，但是linux是没有启用这个选项的，cmd窗口告知巡检失败了。

linux巡检，secret字段空着就行。
另外建议使用管理员身份运行.exe程序。

**Comment by zZzZhangjh** [comment]
我用了管理员运行，然后secret空着还是不行
这样子的，我是自己开了虚拟机运行kylin系统，然后想测试下能不能用，我自己用xshell测试用户名和密码是正确能登陆kylin系统的。
我运行这个exe，按照您的指引，空着secret还是会提示    “设备 kylin Enable密码认证失败！”
然后打开01log.log里面没有巡检内容。

**Comment by icefire-ken** [comment]
> 我用了管理员运行，然后secret空着还是不行 这样子的，我是自己开了虚拟机运行kylin系统，然后想测试下能不能用，我自己用xshell测试用户名和密码是正确能登陆kylin系统的。 我运行这个exe，按照您的指引，空着secret还是会提示 “设备 kylin Enable密码认证失败！” 然后打开01log.log里面没有巡检内容。

https://kylinos.cn/support/download.html
是这个地址的银河麒麟桌面操作系统吗？

**Comment by zZzZhangjh** [comment]
应该是，我都忘记是哪里下载的了，哈哈..我这边的麒麟是这个文件安装的
Kylin-Server-10-SP2-Release-Build09-20210524-x86_64.iso

但是我觉得应该不关事。
毕竟我手动能巡检的，只是运行这个.exe程序，不知道是哪里卡住了，我用pycharm看了下源代码，暂时看不出啥....
