### ISSUE TITLE
telnet测试华三交换机进行巡检，enable密码为空，仍提示enable密码认证失败

### ISSUE THREAD

**Issue by darcy212** [icefire-ken/devices_inspection#7]
telnet测试华三交换机进行巡检，enable密码为空，仍提示enable密码认证失败

**Comment by icefire-ken** [comment]
> telnet测试华三交换机进行巡检，enable密码为空，仍提示enable密码认证失败

用今天更新的程序试试，应该已经修复了。

**Comment by darcy212** [comment]
可以了，感谢
