### ISSUE TITLE
巡检华为交换机问题

### ISSUE THREAD

**Issue by dxche2003** [icefire-ken/devices_inspection#8]
会报管理地址或端口不可达，实际上securecrt可以正常连接，另外，在巡检大量设备的时候，有可能会报执行命令 "display current-configuration" 时，设备 192.168.253.119 出现异常：
Pattern not detected: 'display\\ ospf\\ interfa' in output.

Things you might try to fix this:
1. Explicitly set your pattern using the expect_string argument.
2. Increase the read_timeout to a larger value.类似这样的错误，这个错误出现的比较薛定谔

**Comment by dxche2003** [comment]
补充下，选择huawei_telnet，端口选23可以脚本正常通过telnet协议连接，但是选huawei，端口选22，不能通过ssh连接

**Comment by dxche2003** [comment]
huawei设备无法通过ssh连接的问题找到了，需要增加连接阶段的超时时间到15s

**Comment by icefire-ken** [comment]
> huawei设备无法通过ssh连接的问题找到了，需要增加连接阶段的超时时间到15s

你说的是ConnectHandler函数的参数conn_timeout，是吧？

**Comment by dxche2003** [comment]
是的




无名
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "icefire-ken/devices_inspection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月17日(星期三) 晚上9:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [icefire-ken/devices_inspection] 巡检华为交换机问题 (Issue #8)





  
huawei设备无法通过ssh连接的问题找到了，需要增加连接阶段的超时时间到15s
  
你说的是ConnectHandler函数的参数conn_timeout，是吧？

**Comment by icefire-ken** [comment]
> 是的 无名 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "icefire-ken/devices_inspection" ***@***.***&gt;; 发送时间:&nbsp;2024年7月17日(星期三) 晚上9:59 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [icefire-ken/devices_inspection] 巡检华为交换机问题 (Issue #8) huawei设备无法通过ssh连接的问题找到了，需要增加连接阶段的超时时间到15s 你说的是ConnectHandler函数的参数conn_timeout，是吧？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

我已经添加了相关的参数，你可以再试试
