### ISSUE TITLE
连接超时时间问题

### ISSUE THREAD

**Issue by joyhu** [icefire-ken/devices_inspection#9]
在巡检一批设备时，全部都是华为的，有两台连接有点慢，自己使用putty连接都得多等一会才会出现输入用户名的提示，软件应该是到超时时间了，所以显示设备不可达。这个时间是否可以修改长一些。

**Comment by icefire-ken** [comment]
> 在巡检一批设备时，全部都是华为的，有两台连接有点慢，自己使用putty连接都得多等一会才会出现输入用户名的提示，软件应该是到超时时间了，所以显示设备不可达。这个时间是否可以修改长一些。

我添加了相关参数，你可以再试试。期待你的反馈

**Comment by joyhu** [comment]
> > 在巡检一批设备时，全部都是华为的，有两台连接有点慢，自己使用putty连接都得多等一会才会出现输入用户名的提示，软件应该是到超时时间了，所以显示设备不可达。这个时间是否可以修改长一些。
> 
> 我添加了相关参数，你可以再试试。期待你的反馈

谢谢，过几天测试下。
